// <auto-generated />
using Cosmonaut.Scaler.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Cosmonaut.Scaler.Server.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20190227145736_Added_Cosmos_Accounts")]
    partial class Added_Cosmos_Accounts
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0-preview.19074.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Cosmonaut.Scaler.Server.Data.Models.CosmosAccount", b =>
                {
                    b.Property<string>("Endpoint")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("MasterKey");

                    b.HasKey("Endpoint");

                    b.ToTable("CosmosAccounts");
                });
#pragma warning restore 612, 618
        }
    }
}
